# General configuration for this plugin
General:
  # If this plugin should be enabled
  # Default: true
  Enable: true

  # What is the interval between weathers
  Interval:
    # The minimal time between different weathers (in seconds; will be at least 30)
    # Default: 180 (min: 30; max: 1800)
    MinTime: 180
    # The maximum time between different weathers (in seconds)
    # Default: 900 (min: 30; max: 1800)
    MaxTime: 900
    # true = random number between MinTime and MaxTime
    # false = a semi-random, more middle-average number between MinTime and MaxTime
    # Default: true
    Random: true

  # The chance that a weather occurs per interval
  # Default: 1.0 (min: 0.0; max: 1.0)
  WeatherLikelihood: 1.0


Rain:
  # We(a)ther or not this weather will occur
  # Default: true
  EnableWeather: true

  # Will pick a random duration for this weather between MinDuration and MaxDuration
  Duration:
    # The minimal duration of windy weather (in seconds)
    # Default: 90 (min: 30; max: 1200)
    MinDuration: 90
    # The maximum duration of windy weather (in seconds)
    # Default: 240 (min: 30; max: 1200)
    MaxDuration: 240



  # This determines how likely an occurrence of this weather-type is compared to another
  # Default: 2 (min: 1; max: 10; whole numbers)
  Weight: 2


# Windy represents a windy weather, which slows down players that walk towards the wind
# and speeds up players that walk with the wind; it also generates fancy particles
Windy:
  # We(a)ther or not this weather will occur
  # Default: true
  EnableWeather: true

  # Will pick a random duration for this weather between MinDuration and MaxDuration
  Duration:
    # The minimal duration of this weather (in seconds)
    # Default: 120 (min: 30; max: 1200)
    MinDuration: 120
    # The maximum duration of this weather (in seconds)
    # Default: 210 (min: 30; max: 1200)
    MaxDuration: 210

  # If AffectPlayers and EnableParticles are both false, EnableWeather will be considered false, too
  # Should the wind affect players? (e.g. slow them down or speed them up)
  # Default: true
  AffectPlayers: true
  # If this weather should generate particles
  # Default: true
  EnableParticles: true

  # This determines how likely an occurrence of this weather-type is compared to another
  # So, a weather with a weight of 2 is twice as likely to occur as a weather with a weight of 1
  # Default: 1 (min: 1; max: 10; whole numbers)
  Weight: 1




