name: SasaWeather
version: 1.0
main: Suppenknecht.SasaWeather.Main

commands:
  sweather:
    description: Changes the weather
    usage: /weather [type]

  enabledweather:
    description: Lists the enabled weather types.
    usage: /enabledweather